### ISSUE TITLE
Start session return validation failure "No enum match for: iPhone OS" on iOS 9 or earlier

### ISSUE THREAD

**Issue by ZhangChenglong** [comapi/comapi-sdk-ios#4]
The default value of AuthorizeSessionTemplate.Body.platform is UIDevice.current.systemName, which returns "iPhone OS" on iOS 9 or earlier. It then cause starting session validation failure. On iOS 10 it returns "iOS" which can pass the validation of session.

**Comment by tomaszmaciejko** [comment]
Hello @ZhangChenglong,

As we investigated, the problem is indeed present in our code. The fix is ready and waiting for the review before merging to **master**.

Till then you can point to the **dev** branch in your Podfile.

Thanks,
Tomasz

**Comment by ZhangChenglong** [comment]
Hi @tomaszmaciejko ,

After switching to dev branch, new issues came out when loading messages. Please see the screenshot attached.
![image](https://user-images.githubusercontent.com/1720540/29590264-1610cb3c-87ed-11e7-9f81-9f335ee99e74.png)

Thanks,
Chenglong

**Comment by tomaszmaciejko** [comment]
Hello @ZhangChenglong,

I have provided a fix for the issue described above on the **dev** branch. Please update your pods and check if it works now. 

Please ask if you have any other questions or need further assistance.

Thanks,
Tomasz

**Comment by ZhangChenglong** [comment]
Hi @tomaszmaciejko ,

It works now. Can you please merge this piece of code into master branch?

Thanks,
Chenglong
