### ISSUE TITLE
startSession failed branch swift 4

### ISSUE THREAD

**Issue by erolando** [comapi/comapi-sdk-ios#7]
startSession failed branch swift 4

return message "responseParsingFailed(ComapiFoundation.RequestTemplatePerformingError.ResponseParsingFailedInfo"

**Comment by dkowalsky92** [comment]
Hey @erolando,

We no longer support the Swift version of the SDK. Take a look at https://github.com/comapi/comapi-sdk-ios-objc.

Best regards,
Dominik
